<?php

return array(
    '首页'    => array(
        'cateType' => 'Index',
        'isSub' => 0,
        'icon'  => 'sf-house',
        'ctrl'  => 'Default', 
        'href'  => '/',
    ),
    '聚合内容管理' => array(
        'cateType' => 'Rss',
        'isSub' => 1,
        'icon'  => 'sf-rss',
        'href'  => '',
        'subMenu' => array(
            array(
                'text'   => '文章管理(外链)',
                'href'   => 'http://chenjt.ams.test.zol.com.cn/index.php?c=Platform',
                'ctrl'   => 'Ams',
                'target' => '_blank',
            ),
            array(
                'text'   => '帖子管理',
                'href'   => '/?c=RecBbs',
                'ctrl'   => 'RecBbs',
                'target' => '',
            ),
            array(
                'text'   => '问答管理',
                'href'   => '/?c=RecAsk',
                'ctrl'   => 'RecAsk',
                'target' => '',
            ),
            array(
                'text'   => '好说管理',
                'href'   => '/?c=RecHaoshuo',
                'ctrl'   => 'RecHaoshuo',
                'target' => '',
            ),
            array(
                'text'   => '攒机单管理',
                'href'   => '/?c=RecDiy',
                'ctrl'   => 'RecDiy',
                'target' => '',
            ),
            array(
                'text'   => '课堂管理',
                'href'   => '/?c=RecClass',
                'ctrl'   => 'RecClass',
                'target' => '',
            ),
            array(
                'text'   => '大数据后台(外链)',
                'href'   => 'http://recadmin.zol.com.cn//index.php/Item/Zol/show',
                'ctrl'   => 'Bigdata',
                'target' => '_blank',
            ),
        ),
    ),
    'ZOL内容管理' => array(
        'cateType' => 'Cms',
        'isSub' => 1,
        'icon'  => 'sf-file-word',
        'href'  => '',
        'subMenu' => array(
            array(
                'text'   => '原创频道',
                'href'   => '/?c=DocSubject',
                'ctrl'   => 'DocSubject',
                'target' => '',
            ),
            array(
                'text'   => '内容包版',
                'href'   => '/?c=Package',
                'ctrl'   => 'Package',
                'target' => '',
            ),
            array(
                'text'   => '频道管理',
                'href'   => '/?c=ChannelMana',
                'ctrl'   => 'ChannelMana',
                'target' => '',
            ),
            array(
                'text'   => '话题文章',
                'href'   => '/?c=TopicArticle',
                'ctrl'   => 'TopicArticle',
                'target' => '',
            ),
            array(
                'text'   => '搜索热词',
                'href'   => '/?c=SearchIndex',
                'ctrl'   => 'SearchIndex',
                'target' => '',
            ),
            array(
                'text'   => '列表下拉文案',
                'href'   => '/?c=DocumentsRefresh',
                'ctrl'   => 'DocumentsRefresh',
                'target' => '',
            ),
            array(
                'text'   => '轻量化资讯',
                'href'   => '/?c=LightWeightInfo',
                'ctrl'   => 'LightWeightInfo',
                'target' => '',
            ),
            array(
                'text'   => '刷TS缓存',
                'href'   => '/?c=ClearCache',
                'ctrl'   => 'ClearCache',
                'target' => '',
            ),
            array(
                'text'   => '手工位聚合',
                'href'   => '/?c=ManageModuleContent',
                'ctrl'   => 'ManageModuleContent',
                'target' => '',
            ),
            array(
                'text'   => '好说评论管理',
                'href'   => '/?c=HaoshuoComment',
                'ctrl'   => 'HaoshuoComment',
                'target' => '',
            ),
        ),
    ),
    '公共功能' => array(
        'cateType' => 'Pub',
        'isSub' => 1,
        'icon'  => 'sf-brick',
        'href'  => '',
        'subMenu' => array(
            array(
                'text' => '消息推送(外链)',
                'href' => 'http://article.zol.com.cn/admin/apppush/?c=Index&a=Form',
                'ctrl' => 'Apppush',
                'target' => '_blank',
            ),
            array(
                'text' => '建议反馈',
                'href' => '/?c=Feedback',
                'ctrl' => 'Feedback',
                'target' => '',
            ),
            array(
                'text' => '常见问题',
                'href' => '/?c=AddArticle',
                'ctrl' => 'AddArticle',
                'target' => '',
            ),
            array(
                'text' => '推送提醒',
                'href' => '/?c=UpdateNotice',
                'ctrl' => 'UpdateNotice',
                'target' => '',
            ),
            array(
                'text' => '关于页面',
                'href' => '/?c=AboutPage',
                'ctrl' => 'AboutPage',
                'target' => '',
            ),
            array(
                'text' => '渠道号管理',
                'href' => '/?c=WapClientChannel',
                'ctrl' => 'WapClientChannel',
                'target' => '',
            ),
            array(
                'text' => '马甲关联',
                'href' => '/?c=NameCorresponding',
                'ctrl' => 'NameCorresponding',
                'target' => '',
            ),
            array(
                'text' => '微信推广二维码',
                'href' => '/?c=WxAbout',
                'ctrl' => 'WxAbout',
                'target' => '',
            ),
            array(
                'text' => '微信小程序信息管理',
                'href' => '/?c=WxInfoManage',
                'ctrl' => 'WxInfoManage',
                'target' => '',
            ),
            array(
                'text' => 'App签到活动',
                'href' => '/?c=AppSign',
                'ctrl' => 'AppSign',
                'target' => '',
            ),
            array(
                'text' => '非法词汇管理',
                'href' => '/?c=IllWord',
                'ctrl' => 'IllWord',
                'target' => '',
            ),
        ),
    ),
    '广告管理' => array(
        'cateType' => 'Ad',
        'isSub' => 1,
        'icon'  => 'sf-shop',
        'href'  => '',
        'subMenu' => array(
            array(
                'text' => '节庆包版',
                'href' => '/?c=FestivalBaoBan',
                'ctrl' => 'FestivalBaoBan',
                'target' => '',
            ),
            array(
                'text'   => '浮层浮钮',
                'href'   => '/?c=ActiveIn',
                'ctrl'   => 'ActiveIn',
                'target' => '',
            ),
            array(
                'text' => '手工位聚合',
                'href' => '/?c=ManageModuleBd',
                'ctrl' => 'ManageModuleBd',
                'target' => '',
            ),
            array(
                'text' => '小程序推荐位',
                'href' => '/?c=MiniProgramAd',
                'ctrl' => 'MiniProgramAd',
                'target' => '',
            ),
        ),
    ),
    'UGC激励' => array(
        'cateType' => 'Promotion',
        'isSub' => 1,
        'icon'  => 'sf-money',
        'href'  => '',
        'subMenu' => array(
            array(
                'text' => '返利商品管理',
                'href' => '/?c=Promotion_GoodsList',
                'ctrl' => 'Promotion_GoodsList',
                'target' => '',
            ),
            array(
                'text'   => '规则设置',
                'href'   => '/?c=Promotion_PromotionSet',
                'ctrl'   => 'Promotion_PromotionSet',
                'target' => '',
            ),
            array(
                'text' => '订单管理',
                'href' => '/?c=Promotion_OrdersList',
                'ctrl' => 'Promotion_OrdersList',
                'target' => '',
            ),
//            array(
//                'text' => '文章统计',
//                'href' => '/?c=Promotion_DocStatistic',
//                'ctrl' => 'Promotion_DocStatistic',
//                'target' => '',
//            ),
            array(
                'text' => '资金管理',
                'href' => '/?c=Promotion_Funds',
                'ctrl' => 'Promotion_Funds',
                'target' => '',
            ),
            array(
                'text' => '提现管理',
                'href' => '/?c=Promotion_CashList',
                'ctrl' => 'Promotion_CashList',
                'target' => '',
            ),
            array(
                'text' => 'QA管理',
                'href' => '/?c=Promotion_Qa',
                'ctrl' => 'Promotion_Qa',
                'target' => '',
            ),
        ),
    ),
    '社交PK' => array(
        'cateType' => 'PkSocial',
        'isSub' => 1,
        'icon'  => 'sf-gamepad',
        'href'  => '',
        'subMenu' => array(
            array(
                'text' => '提问审核',
                'href' => '/?c=Pksocial_AskList',
                'ctrl' => 'Pksocial_AskList',
                'target' => '',
            ),
            array(
                'text' => '回答审核',
                'href' => '/?c=Pksocial_AnswerList',
                'ctrl' => 'Pksocial_AnswerList',
                'target' => '',
            ),
            array(
                'text'   => 'PK讨论审核',
                'href'   => '/?c=Pksocial_CommentList',
                'ctrl'   => 'Pksocial_CommentList',
                'target' => '',
            ),

        ),
    ),
);